name: Twice Daily Instagram Post

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6,17 * * *'  # 08:00 & 19:00 Belgische tijd (UTC+2)

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run script
        run: python scripts/generate_and_post.py
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
          META_BUSINESS_ID: ${{ secrets.META_BUSINESS_ID }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          **STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}**  # ✅ DIT IS DE NIEUWE REGEL
