name: Daily Instagram Post
on:
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Generate and post to Instagram
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          INSTA_ACCESS_TOKEN: ${{ secrets.INSTA_ACCESS_TOKEN }}
          INSTA_BUSINESS_ID: ${{ secrets.INSTA_BUSINESS_ID }}
        run: python scripts/generate_and_post.py
